version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: novafit-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - novafit_postgres_data:/var/lib/postgresql/data
    networks:
      - novafit_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: novafit-keycloak
    env_file:
      - .env
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev --http-port=8080
    ports:
      - "8080:8080"
    networks:
      - novafit_net

  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    container_name: novafit-api-placeholder
    command: ["sh", "-c", "echo 'Integrar imagen de la API en el siguiente sprint'; sleep 3600"]
    ports:
      - "${BACKEND_PORT}:5000"
    networks:
      - novafit_net
    depends_on:
      - postgres
      - keycloak

volumes:
  novafit_postgres_data:

networks:
  novafit_net:
